[[language]]
auto-format = true
name = "nix"

[[language]]
auto-format = true
formatter = {command = "mdformat", args = ["-"]}
language-servers = ["marksman"]
name = "markdown"

[language-server.nixd]
args = ["--semantic-tokens=true"]
command = "nixd"

[language-server.nixd.config.nixd.formatting]
command = ["alejandra"]

[language-server.nixd.config.nixd.nixpkgs]
expr = "import (builtins.getFlake \"/home/llego/nixconfig\").inputs.nixpkgs { }"

[language-server.nixd.config.nixd.options.nixos]
expr = "(builtins.getFlake \"/home/llego/nixconfig\").nixosConfigurations.laptop.options"
