[backdrop]
enabled = false

[bar.default]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
start = [ "workspaces", "active_window" ]


[shell]
niri_overview_type_to_launch_enabled = true

[theme]
builtin = "Rosé Pine"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "niri" ]
    community_ids = [ "zen-browser" ]

[wallpaper]
directory = "/home/llego/nixconfig/dots/noctalia/wallpapers"
transition = [ "wipe" ]

[widget.battery]
capsule = true
display_mode = "graphic"

[widget.brightness]
capsule = true

[widget.network]
show_label = false

[widget.volume]
capsule = true
