[gotify]
url = "wss://gotify.cri.su:443"
token = { command = "cat /run/agenix/gotify-desktop-token" }

# optional, if true, deletes messages that have been handled, defaults to false
# auto_delete = true

[notification]
# optional, ignores messages with priority lower than given value, defaults to 0
min_priority = -1

# [action]
# optional, run the given command for each message, with the following environment variables set: GOTIFY_MSG_PRIORITY, GOTIFY_MSG_TITLE and GOTIFY_MSG_TEXT.
# on_msg_command = "/usr/bin/beep"
