{
  modulesPath,
  username,
  inputs,
  pkgs,
  ...
}: {
  system.stateVersion = "24.05";

  # users.users.root.openssh.authorizedKeys.keys = [
  #   # change this to your ssh key
  #   "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFcYhLnYhEmrmWViN9z9VgEQPInZ/WxSCAgDV5rj4lpj mail@christiansandberg.fi"
  # ];

  imports = [
    inputs.disko.nixosModules.disko
    ./../modules/core.nix
    ./../modules/basic-cli.nix
    # ./../modules/storj-backup.nix
    ./crisuflix-disk-config.nix
    # Hardware config will be generated by nixos-anywhere during installation
    ./crisuflix-hardware-configuration.nix
  ];

  # Boot configuration
  boot = {
    # Boot loader
    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 10;
      };
      efi.canTouchEfiVariables = true;
    };

    # Kernel settings
    kernel.sysctl = {
      "fs.inotify.max_user_watches" = 524288; # For media servers, file sync, dev tools
      "fs.inotify.max_user_instances" = 512; # For multiple Docker containers
    };

    # Filesystem support
    supportedFilesystems = ["zfs"];

    # ZFS configuration
    zfs = {
      forceImportRoot = false;
      extraPools = ["illby" "veckjarvi"]; # Import existing pools from TrueNAS
    };
  };

  # Required for ZFS - from existing TrueNAS
  networking.hostId = "447b046a";

  # ZFS services
  services.zfs = {
    autoScrub = {
      enable = true;
      interval = "monthly";
      pools = ["illby" "veckjarvi"];
    };
    trim = {
      enable = true;
      interval = "weekly";
    };
  };

  # # Use sanoid for flexible snapshot management
  # services.sanoid = {
  #   enable = true;

  #   templates.default = {
  #     frequently = 4; # 15-min intervals
  #     hourly = 24;
  #     daily = 7;
  #     weekly = 4;
  #     monthly = 12;
  #     autosnap = true;
  #     autoprune = true;
  #   };

  #   datasets = {
  #     "illby" = {
  #       useTemplate = ["default"];
  #       recursive = true;
  #     };
  #     "illby/transient" = {
  #       autosnap = false;
  #       autoprune = false;
  #     };
  #     "veckjarvi" = {
  #       useTemplate = ["default"];
  #       recursive = true;
  #     };
  #     "veckjarvi/frigate-storage" = {
  #       autosnap = false;
  #       autoprune = false;
  #     };
  #   };
  # };

  # Docker
  virtualisation.docker.enable = true;
  users.users.${username}.extraGroups = ["docker"];

  # Tailscale
  services.tailscale = {
    enable = true;
    extraSetFlags = ["--operator=${username}"];
  };

  # # NFS Server
  # services.nfs.server = {
  #   enable = true;
  #   exports = ''
  #     /mnt/veckjarvi/media/filmer 192.168.1.0/24(sec=sys,rw,anonuid=568,anongid=568,all_squash,no_subtree_check)
  #     /mnt/veckjarvi/media/tv 192.168.1.0/24(sec=sys,rw,anonuid=568,anongid=568,all_squash,no_subtree_check)
  #     /mnt/veckjarvi/backups/haos-backup 192.168.1.0/24(sec=sys,rw,anonuid=3001,all_squash,no_subtree_check)
  #     /mnt/illby/docker/data 192.168.1.214(sec=sys,rw,anonuid=0,all_squash,no_subtree_check)
  #     /mnt/illby/docker/stacks 192.168.1.214(sec=sys,rw,anonuid=0,anongid=0,all_squash,no_subtree_check)
  #   '';
  # };

  # OpenSSH with hardening
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
    };
  };

  # fail2ban for SSH protection
  services.fail2ban = {
    enable = true;
    maxretry = 5;
    bantime = "1h";
  };

  # Network bridges (matching TrueNAS setup)
  networking = {
    useDHCP = false;
    networkmanager.enable = false;

    bridges = {
      br0 = {
        interfaces = ["enp5s0"];
      };
      br1 = {
        interfaces = ["enp6s0"];
      };
    };

    interfaces = {
      br0.ipv4.addresses = [
        {
          address = "192.168.1.101";
          prefixLength = 24;
        }
        {
          address = "192.168.1.103";
          prefixLength = 24;
        }
      ];
      br1.ipv4.addresses = [
        {
          address = "192.168.3.103";
          prefixLength = 24;
        }
      ];
    };

    defaultGateway = {
      address = "192.168.1.1";
      interface = "br0";
    };

    nameservers = ["192.168.1.1"];

    # Firewall
    firewall = {
      enable = true;
      allowedTCPPorts = [
        22 # SSH
        111 # NFS rpcbind
        2049 # NFS
        20048 # NFS mountd
        3493 # NUT (UPS monitoring)
      ];
      allowedUDPPorts = [
        111 # NFS rpcbind
        2049 # NFS
        20048 # NFS mountd
      ];
    };
  };

  # # Additional packages useful for NAS management
  # environment.systemPackages = with pkgs; [
  #   zfs
  #   iotop
  #   smartmontools
  #   lm_sensors
  #   nfs-utils
  # ];

  # # Enable SMART monitoring for disk health
  # services.smartd = {
  #   enable = true;
  #   autodetect = true;
  # };

  # # UPS Configuration (NUT - Network UPS Tools)
  # power.ups = {
  #   enable = true;
  #   mode = "standalone";
  #   ups."ups" = {
  #     driver = "usbhid-ups";
  #     port = "auto";
  #   };
  # };
}
