{ inputs, pkgs, username, ...}:
{
  imports = [ inputs.niri.nixosModules.niri ];
  
  home-manager.users.${username}.imports = [ 
    ./home-manager/user/fuzzel.nix
    ./home-manager/user/kanshi.nix
    ./home-manager/user/niri.nix
    ./home-manager/user/waybar.nix
    ./home-manager/user/wlogout.nix
    #./home-manager/user/xwayland-satellite.nix
  ]; 
  
  environment.systemPackages = [ 
    #pkgs.greetd.tuigreet
    pkgs.xwayland-satellite
    pkgs.wayland-utils
  ];
  
  environment.variables.NIXOS_OZONE_WL = "1";
    
  niri-flake.cache.enable = true;
  programs.niri.enable = true;
  
  # Extra Portal Configuration
  /*xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal
    ];
    configPackages = [
      pkgs.xdg-desktop-portal-gtk
      #pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal
    ];
  }; */
  
  services = {
    blueman.enable = true;   # Bluetooth
    gvfs.enable = true;      # Nautilus sftp
    xserver = {
      enable = true;
      displayManager.gdm.enable = true;
      xkb = {
        layout = "fi";
        variant = "";
      };
    };
    /*greetd = {
      enable = true;
      vt = 3;
      settings = {
        default_session = {
          # Wayland Desktop Manager is installed only for user ryan via home-manager!
          user = username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          #command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
          command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd niri-session"; # start niri with a TUI login manager
        };
      };
    }; */
  };

}
