{
  security.pki.certificates = [
    ''
      sand.berg
      =========
      -----BEGIN CERTIFICATE-----
      MIID0TCCArmgAwIBAgIUBflOznOEY4qn61TrPPdeUKJRFXIwDQYJKoZIhvcNAQEL
      BQAweDELMAkGA1UEBhMCRkkxDjAMBgNVBAgMBUlsbGJ5MRUwEwYDVQQHDAxEZWZh
      dWx0IENpdHkxEjAQBgNVBAoMCXNhbmQuYmVyZzESMBAGA1UEAwwJc2FuZC5iZXJn
      MRowGAYJKoZIhvcNAQkBFgttYWlsQGNyaS5zdTAeFw0yNDA2MDkxMDEwMjBaFw0y
      NjA2MDkxMDEwMjBaMHgxCzAJBgNVBAYTAkZJMQ4wDAYDVQQIDAVJbGxieTEVMBMG
      A1UEBwwMRGVmYXVsdCBDaXR5MRIwEAYDVQQKDAlzYW5kLmJlcmcxEjAQBgNVBAMM
      CXNhbmQuYmVyZzEaMBgGCSqGSIb3DQEJARYLbWFpbEBjcmkuc3UwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCsYpDzONmtajYcleMtdZNbi3n1A0ZSulD
      sqnSd4PGlc3swdTPc/R+jH/UmMgBntRYLUO6ZPhUX8yK+qRyWMMSLKHQI5reXQIm
      sqSbBObHBdaCtoM8n5bRWxVJ8xLfeBcn2wNdEjxaPjGJPCAXj/g27vXpn8PbKF+t
      L1JBWqlQ3kwse9M91Y20gltnQ0Cqikx8AYtnatlDtbPVjclnqdiUpOlHFzMBtwYg
      LfD1+KEJ3CHRkjeuTjVBSzoC1EAIXg2c5NXqDSs5OyJxl6SZAnyWA2N1B6Co2eN8
      ZKOq09EAHtxYPeuaWNrITwpDk093Wfil+ZZFwZLXhv28wdQmbLrBAgMBAAGjUzBR
      MB0GA1UdDgQWBBS6yFElaPj2MpY3JLHspMDDYE9G2DAfBgNVHSMEGDAWgBS6yFEl
      aPj2MpY3JLHspMDDYE9G2DAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
      A4IBAQCFFpLT2mFfWvYSv0RWr2R/QMiopQm9qlnpv6k9g0jMW6w+7nLmqKYjZVXq
      qsAcm3nZjqIgITuGzaJOk+c/G/r1NRk+KWzQaL7Rlyt+5VCdlyPsB/9POpks1HzT
      Y5lPgL/qiLJc1p3QVb5gbiR5kurbFyNvEOJw9U7oP9wHD3krioBiaCSjTrJW/Nh3
      T/NWi6SgVYZtVuxwvWFl6e6x+htzSgVJ3m8XKg/fc6A/eOdb0cQ65X7dFNktu0cp
      2roKEhhnDNgPQLqKE9E8U9vppZ9Pf+oOPsWfUK1a4dFzBM/rnBClJqCqmEip6XG6
      zR2LGU+xnr1tsr6VqfdMFDTbI4OD
      -----END CERTIFICATE-----
      unifi
      =========
      -----BEGIN CERTIFICATE-----
      MIIDNTCCAh2gAwIBAgIJXywE8r1K1BWLMA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
      BAMTC3VuaWZpLmxvY2FsMB4XDTIzMDkyNjIwMTMwNVoXDTI1MTIyOTIwMTMwNVow
      FjEUMBIGA1UEAxMLdW5pZmkubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
      ggEKAoIBAQDn9crA8bRB0KSqRSTvwI7s487FEF4vmAh1mF3q/UPt3OPLMopdaIUd
      umlGxJ67puuzz4htmwQMEJSylOt+RTp49fLNtOqOI721bqSb0hTmQBt3I8jjoGTd
      sP75nrVoQLmVRvIH6cTWs9AXaefo3b2EZYYJZJh8ufvZz9gfMXKIOiz7xcbLT0EI
      BuRqebHUngalpMS8iJ3/3wRZOsFRTlRdUT8tIKLc3IumghqA9xUnYw7cEvoqt+ra
      Bq/L0F0MN6uy0Vb/Qo/PmdYg1fwY0+yQ4gdGVVdNbqQ9Vo5eH60rkFU8Q8Y10XZ2
      rWBmMJZwoy3uBCC8Io8Nb9CID25MlwtRAgMBAAGjgYUwgYIwCwYDVR0PBAQDAgL0
      MDEGA1UdJQQqMCgGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUF
      BwMIMEAGA1UdEQQ5MDeCC3VuaWZpLmxvY2Fsgglsb2NhbGhvc3SCBVs6OjFdhwR/
      AAABhxD+gAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IBAQBm7tfAOIkA
      38wgPEdCVwivMrzBBeby8nRlYJUYvsAiL6fW2he2jGvUzdWNd2i6MpJXPGUevz6V
      KWtFqBPopWYnl2/1Mbm9IZQQhHnYBK0bPaC2xgOsedv1xKXza4T3qaO2dw+ZlfJ0
      HuFq6fTv50KZfETjg2MUZYgCrTDyqGLYM8iaJwJrrMBUJI2ZXGBg5Hs0j+N4OXiv
      2O/rvDZAdZDJJj2GoeaZTAvsDThS9F2cL2Pp72mTVsmMSEYzJEa3+edc0vQTmvtx
      2afDxkbF7mCJsavz98F/QZfH1h9jRLpM1xWWF7wp6C3bKlVdN3Vn6sX0Gi81uF9X
      8uw0tbYzvoMD
      -----END CERTIFICATE-----
    ''
  ];
}
