{
  inputs,
  config,
  pkgs,
  username,
  ...
}: {
  imports = [
    inputs.noctalia.nixosModules.default
  ];

  # Niri window manager
  programs.niri.enable = true;

  # Noctalia shell
  services.noctalia-shell.enable = true;

  environment.systemPackages = with pkgs; [
    pavucontrol
    xwayland-satellite
    wayland-utils
    fuzzel
    brightnessctl
    wlr-randr
    wdisplays
    wl-clipboard
  ];

  # Environment variables
  environment = {
    variables = {
      NIXOS_OZONE_WL = "1"; # For electron applications such as vscode
    };
    sessionVariables = {
      EDITOR = "nano";
      FLAKE = "/home/${username}/nixconfig"; # Needed by nh to work from any dir
      TERMINAL = "alacritty";
      SAL_USE_VCLPLUGIN = "kf5"; # try to get dark mode working in libreoffice
    };
  };

  # Extra Portal Configuration
  # xdg-desktop-portal provides a portal frontend service for
  # Flatpak, Snap, and possibly other desktop containment/sandboxing frameworks.
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal
    ];
    configPackages = [
      pkgs.xdg-desktop-portal-gtk
      #pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal
    ];
  };

  services = {
    blueman.enable = true; # Bluetooth
    gvfs.enable = true; # Nautilus sftp
    greetd = {
      enable = true;
      #vt = 3;
      settings = {
        default_session = {
          # Wayland Desktop Manager is installed only for user ryan via home-manager!
          user = username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          #command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
          #command = "${pkgs.tuigreet}/bin/tuigreet --remember --cmd niri-session --theme 'border=${config.lib.stylix.colors.base08};text=${config.lib.stylix.colors.base09};prompt=green;time=red;action=blue;button=yellow;container=black;input=${config.lib.stylix.colors.base0F}'";
          command = ''
            ${pkgs.tuigreet}/bin/tuigreet \
              --time \
              --asterisks \
              --user-menu \
              --remember \
              --cmd niri-session \
              --theme 'border=magenta;text=white;prompt=cyan;time=green;action=blue;button=yellow;container=black;input=brightmagenta'
          '';
        };
      };
    };
  };

  fonts.packages = with pkgs; [
    nerd-fonts.droid-sans-mono
    nerd-fonts.fira-code
    noto-fonts-color-emoji
    inter
  ];

  home-manager.users.${username} = {
    gtk = {
      enable = true;
      font = {
        package = pkgs.inter;
        name = "Inter Display Regular";
        size = 10;
      };
      colorScheme = "dark";
      theme = {
        package = pkgs.tokyonight-gtk-theme;
        name = "Tokyonight-Dark";
      };
      iconTheme = {
        package = pkgs.papirus-icon-theme;
        name = "Papirus-Dark";
      };
      cursorTheme = {
        package = pkgs.numix-cursor-theme;
        name = "Numix-Cursor-Light";
        size = 24;
      };
    };

    xdg = {
      mimeApps.enable = true;
      mimeApps.defaultApplications = {
        "default-web-browser" = "firefox.desktop";
        "text/plain" = "org.gnome.TextEditor.desktop";
        "text/html" = "firefox.desktop";
        "x-scheme-handler/http" = "firefox.desktop";
        "x-scheme-handler/https" = "firefox.desktop";
        "x-scheme-handler/about" = "firefox.desktop";
        "x-scheme-handler/unknown" = "firefox.desktop";
        "x-scheme-handler/mailto" = "proton-mail.desktop";
        "application/xhtml+xml" = "firefox.desktop";
        "application/octet-stream" = "vlc.desktop";
        "application/pdf" = "org.gnome.Evince.desktop";
        "image/jpeg" = "org.gnome.Loupe.desktop";
        "image/png" = "org.gnome.Loupe.desktop";
        "image/gif" = "org.gnome.Loupe.desktop";
        "image/webp" = "org.gnome.Loupe.desktop";
        "image/bmp" = "org.gnome.Loupe.desktop";
      };
      configFile."mimeapps.list".force = true;
    };
  };

  qt = {
    enable = true;
    platformTheme = "gnome";
    style = "adwaita-dark";
  };

  programs.dconf.profiles.user.databases = [
    {
      settings."org/gnome/desktop/interface".color-scheme = "prefer-dark";
    }
  ];
}
