{
  inputs,
  config,
  pkgs,
  username,
  ...
}: {
  imports = [inputs.niri.nixosModules.niri];

  home-manager.users.${username} = {
    home.sessionVariables = {
      EDITOR = "gnome-text-editor";
      FLAKE = "/home/${username}/nixconfig"; # Needed by nh to work from any dir
      TERMINAL = "alacritty";
    };
    xdg.mimeApps.enable = true;
    xdg.mimeApps.defaultApplications = {
      "default-web-browser" = "firefox.desktop";
      "text/plain" = "org.gnome.TextEditor.desktop";
      "text/html" = "firefox.desktop";
      "x-scheme-handler/http" = "firefox.desktop";
      "x-scheme-handler/https" = "firefox.desktop";
      "x-scheme-handler/about" = "firefox.desktop";
      "x-scheme-handler/unknown" = "firefox.desktop";
      "x-scheme-handler/mailto" = "proton-mail.desktop";
      "application/xhtml+xml" = "firefox.desktop";
      "application/octet-stream" = "vlc.desktop";
    };
    xdg.configFile."mimeapps.list".force = true;
    imports = [
      ./home-manager/fuzzel.nix
      ./home-manager/niri.nix
      ./home-manager/swayidle.nix
      ./home-manager/waybar
      ./home-manager/wlogout.nix
      ./home-manager/xwayland-satellite.nix
    ];
  };

  environment.systemPackages = with pkgs; [
    pavucontrol
    xwayland-satellite
    wayland-utils
  ];

  environment.variables.NIXOS_OZONE_WL = "1";

  programs.niri.enable = true;
  niri-flake.cache.enable = true;
  nixpkgs.overlays = [inputs.niri.overlays.niri];
  programs.niri.package = pkgs.niri-stable;
  #programs.niri.package = pkgs.niri;

  # Extra Portal Configuration
  # xdg-desktop-portal provides a portal frontend service for
  # Flatpak, Snap, and possibly other desktop containment/sandboxing frameworks.
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal
    ];
    configPackages = [
      pkgs.xdg-desktop-portal-gtk
      #pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal
    ];
  };

  services = {
    blueman.enable = true; # Bluetooth
    gvfs.enable = true; # Nautilus sftp
    xserver = {
      enable = false;
      displayManager.gdm.enable = false;
      xkb = {
        layout = "fi";
        variant = "";
      };
    };
    greetd = {
      enable = true;
      vt = 3;
      settings = {
        default_session = {
          # Wayland Desktop Manager is installed only for user ryan via home-manager!
          user = username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          #command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
          command = "${pkgs.greetd.tuigreet}/bin/tuigreet --remember --cmd niri-session --theme 'border=${config.lib.stylix.colors.base08};text=${config.lib.stylix.colors.base09};prompt=green;time=red;action=blue;button=yellow;container=black;input=${config.lib.stylix.colors.base0F}'";
        };
      };
    };
  };
}
